name: Quick Validation

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '18'

jobs:
  # Quick Build and Test
  quick-validate:
    name: Quick Validation
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linting
      run: npm run lint
      
    - name: Build project
      run: npm run build
      
    - name: Validate build
      run: npm run validate:build
      
    - name: Test CLI
      run: npm run validate:cli
      
    - name: Run basic tests
      run: npm run test
      
    - name: Check package validation
      run: npm run validate:package
      
    - name: Check bundle size
      run: npm run validate:bundle-size
      
    - name: Check startup time
      run: npm run validate:startup-time
      
    - name: Check memory usage
      run: npm run validate:memory-usage 